import 'slick-carousel/slick/slick.scss';
import 'slick-carousel/slick/slick-theme.scss';
import './searchRoom.scss';
import '../../style.scss';
import '../../../assets/scss/range.scss';
import '../../../blocks/calendar/calendar.scss';
import '../../../blocks/dropDown/dropDown.scss';
import '../../../blocks/filter/filter.scss';
import '../../../blocks/button/button.scss';
import '../../../blocks/footer/footer.scss';
import '../../../blocks/header/header.scss';
import '../../../blocks/slider-range/slider-range.scss';
import '../../../blocks/alone-calendar/alone-calendar.scss';
import '../../../blocks/custom-checkbox/custom-checkbox.scss'
import '../../../blocks/checkbox-double-name/checkbox-double-name.scss'
import '../../../blocks/checkbox-list/checkbox-list.scss'
import '../../../blocks/room-info/room-info.scss'
import '../../../assets/scss/simplePagination.css';
import '../../../blocks/pagination/pagination.scss'

import '../../../js/jquery-3.6.0.min.js';
import '../../../blocks/dropDown/dropDown.js';
import '../../../blocks/dropDown/dropDownInit.js'
import '../../../blocks/slider-range/slider-range-init.js'
import '../../../blocks/alone-calendar/alone-calendar-init.js';
import '../../../blocks/alone-calendar/alone-calendar.js';
import '../../../blocks/checkbox-list/checkbox-list.js'
import '../../../blocks/checkbox-list/checkbox-list-init.js'
import '../../../blocks/room-info/room-info.js'
import '../../../blocks/room-info/room-info-init.js'
import '../../../blocks/pagination/pagination.js'
import '../../../blocks/pagination/pagination-init.js'

