import './style.scss'
import '../blocks/filter/filter.scss'
import '../blocks/button/button.scss'
import '../blocks/dropDown/dropDown.scss'
import '../blocks/footer/footer.scss'
import '../blocks/header/header.scss'
import '../blocks/calendar/calendar.scss'
import '../blocks/calendar/calendar.scss'

import '../js/jquery-3.6.0.min.js'
import '../blocks/dropDown/dropDown'
import '../blocks/dropDown/dropDownInit.js'
// import '../js/datepicker.min.js 
import '../blocks/dropDown/dropDown.js'
import '../blocks/calendar/calendar.js'
import '../blocks/calendar/calendarInit.js'