import './style.scss'
import '../blocks/button/button.scss'
import '../blocks/dropDown/dropDown.scss'
import '../blocks/calendar/calendar.scss'
import '../blocks/range-date-calendar/range-date-calendar.scss'

import '../js/jquery-3.6.0.min.js'
import '../blocks/dropDown/dropDownInit.js'
import '../blocks/dropDown/dropDown.js'
import '../blocks/range-date-calendar/range-date-calendar-init.js'
import '../blocks/range-date-calendar/range-date-calendar.js'
import '../blocks/nav-menu/nav-menu-init.js'
import '../blocks/nav-menu/nav-menu.js'
