import './roomDetails.scss'
import '../../../assets/scss/datepicker.min.scss'
import '../../style.scss'

import '../../../js/jquery-3.6.0.min.js'
import '../../../js/datepicker.min.js' 
import '../../../js/like.js'
import '../../../js/close.js'
import '../../../js/clear.js'
import '../../../js/click.js'
import '../../../js/Chart.js'
// import '../../../js/scriptChart.js'
import '../../../js/datepicker.min.js'