import './roomDetails.scss'
import '../../../blocks/calendar/calendar.scss'
import '../../../assets/scss/Chart.min.css'
import '../../../blocks/filter/filter.scss'
import '../../../blocks/dropDown/dropDown.scss'
import '../../../blocks/button/button.scss';
import '../../style.scss'
import '../../../blocks/footer/footer.scss'
import '../../../blocks/header/header.scss';
import '../../../blocks/about-room/about-room.scss';
import '../../../blocks/impressions-room/impressions-room.scss';

import '../../../js/jquery-3.6.0.min.js'
import '../../../js/datepicker.min.js' 
import '../../../js/like.js'
import '../../../blocks/dropDown/dropDown.js'
import '../../../js/datepicker.min.js'
import '../../../blocks/about-room/about-room.js';
import '../../../blocks/impressions-room/impressions-room.js';
import '../../../blocks/impressions-room/impressions-room-init.js';