import './cards.sass'
import '../../style.scss'
import '../../website-pages/search-room/searchRoom.scss'
import '../../website-pages/registration/Registration.scss'
import '../../website-pages/login/login.scss'
import '../../website-pages/room-details/roomDetails.scss'
import '../../../assets/scss/datepicker.min.scss'
import '../../../assets/scss/range.scss'

import '../../../blocks/dropBlock/dropBlock.js'
import '../../../js/close.js'
import '../../../js/datepicker.min.js' 