import './login.scss'
import '../registration/Registration.scss'
import '../../../blocks/button/button.pug'
import '../../../blocks/footer/footer.scss'
import '../../../blocks/header/header.scss'
import '../../style.scss'

import '../../../blocks/text-input/text-input.scss'
import '../../../blocks/login-card/login-card.scss'
import '../../../blocks/nav-menu/nav-menu.js'